import java.awt.HeadlessException;
import java.util.ArrayList;
import java.util.InputMismatchException;
import javax.swing.Box;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author USER
 */
public class guiOldProgram extends javax.swing.JFrame {

    /**
     * Creates new form guiOldProgram
     */
    public guiOldProgram() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Math Operations");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Distance Coordinates");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Dynamic Array");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Leap Year");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(jButton4)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton3)
                        .addGap(22, 22, 22)))
                .addGap(49, 49, 49))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 128, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jButton4))
                .addGap(80, 80, 80))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        String addA = JOptionPane.showInputDialog(null, "Input year");
        if(Integer.parseInt(addA)%400==0 || Integer.parseInt(addA)%4==0&Integer.parseInt(addA)%100!=0)
            JOptionPane.showMessageDialog(null, addA + " is a leap year.");
        else
            JOptionPane.showMessageDialog(null, addA + " is not a leap year.");
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try{// TODO add your handling code here:
        String initial = JOptionPane.showInputDialog(null, 
                        """
                        1. Addition
                        2. Subtraction
                        3. Multiplication
                        4. Division
                        5. Back to Main Program
                        """);
        switch (Integer.parseInt(initial)){
            case 1 ->{
                String addA = JOptionPane.showInputDialog(null, "Input first number");
                String addB = JOptionPane.showInputDialog(null, "Input second number");
                JOptionPane.showMessageDialog(null, "The answer is " + (Integer.parseInt(addA)+Integer.parseInt(addB)));
            }
            case 2 ->{
                String addA = JOptionPane.showInputDialog(null, "Input first number");
                String addB = JOptionPane.showInputDialog(null, "Input second number");
                JOptionPane.showMessageDialog(null, "The answer is " + (Integer.parseInt(addA)-Integer.parseInt(addB)));
            }
            case 3 ->{
                String addA = JOptionPane.showInputDialog(null, "Input first number");
                String addB = JOptionPane.showInputDialog(null, "Input second number");
                JOptionPane.showMessageDialog(null, "The answer is " + (Integer.parseInt(addA)*Integer.parseInt(addB)));
            }
            case 4 ->{
                String addA = JOptionPane.showInputDialog(null, "Input first number");
                String addB = JOptionPane.showInputDialog(null, "Input second number");
                JOptionPane.showMessageDialog(null, "The answer is " + (Integer.parseInt(addA)/Integer.parseInt(addB)));
            }
            case 5 ->
                System.exit(0);
        }}catch(Exception e){
            JOptionPane.showMessageDialog(null, "Input error occurred", "Error", JOptionPane.ERROR_MESSAGE); 
            System.exit(0);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        JTextField xField = new JTextField(5);
        JTextField yField = new JTextField(5);
        JPanel myPanel = new JPanel();
        myPanel.add(new JLabel("x:"));
        myPanel.add(xField);
        myPanel.add(Box.createHorizontalStrut(15)); // a spacer
        myPanel.add(new JLabel("y:"));
        myPanel.add(yField);
        int x1=0,y1=0,x2=0,y2=0;
        try{
        int result = JOptionPane.showConfirmDialog(null, myPanel, 
               "Please Enter First Coordinate Values", JOptionPane.OK_CANCEL_OPTION);
        if (result == JOptionPane.OK_OPTION) {
            x1 = Integer.parseInt(xField.getText());
            y1 = Integer.parseInt(yField.getText());
        }
        else{
            JOptionPane.showMessageDialog(null, "No Input", "Error", JOptionPane.ERROR_MESSAGE); 
            System.exit(0);
        }
        xField.setText("");
        yField.setText("");
        int result2 = JOptionPane.showConfirmDialog(null, myPanel, 
               "Please Enter Second Coordinate Values", JOptionPane.OK_CANCEL_OPTION);
        if (result2 == JOptionPane.OK_OPTION) {
            x2 = Integer.parseInt(xField.getText());
            y2 = Integer.parseInt(yField.getText());
        }
        else{
            JOptionPane.showMessageDialog(null, "No Input", "Error", JOptionPane.ERROR_MESSAGE); 
            System.exit(0);
        }
        double result3 = Math.sqrt(Math.pow((x2-x1), 2)+(Math.pow((y2-y1), 2)));
        JOptionPane.showMessageDialog(null, "Distance: " + result3);

        }catch(HeadlessException | NumberFormatException e){
                JOptionPane.showMessageDialog(null, "Input error occurred", "Error", JOptionPane.ERROR_MESSAGE); 
                System.exit(0);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        int x, element, origSize;
        int confirm = JOptionPane.YES_OPTION;
        try{
            ArrayList<Integer> array1 = new ArrayList<>();
            while(confirm==JOptionPane.YES_OPTION){
                String addA = JOptionPane.showInputDialog(null, "Input number to the Array. ");
                array1.add(Integer.valueOf(addA));
                int dialogButton = JOptionPane.YES_NO_OPTION;
                confirm = JOptionPane.showConfirmDialog (null, "Do you want to continue?","Warning",dialogButton);                //if(!confirm.equalsIgnoreCase("y")&&!confirm.equalsIgnoreCase("n"))
            }       
            
            while(!array1.isEmpty()){
                String addB = JOptionPane.showInputDialog(null, 
                        "Array: "+ array1 +"  " +
                        "Enter number to delete. ");
                element = Integer.parseInt(addB);
                origSize = array1.size();
                for(x=0;x<array1.size();x++){
                    if(array1.get(x)==element) {
                        array1.remove(x);
                        x--;
                    }
                }
                if(origSize==array1.size())                
                    JOptionPane.showMessageDialog(null, "No number found ", "Error", JOptionPane.ERROR_MESSAGE); 
                else
                    JOptionPane.showMessageDialog(null, "Array " + array1, "Array", JOptionPane.ERROR_MESSAGE); 
            }
            JOptionPane.showMessageDialog(null, "Array is empty. ", "Empty", JOptionPane.ERROR_MESSAGE); 
        } catch (InputMismatchException e) {
            JOptionPane.showMessageDialog(null, "Input error occurred ", "Error", JOptionPane.ERROR_MESSAGE); 
            System.exit(0);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(guiOldProgram.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(guiOldProgram.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(guiOldProgram.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(guiOldProgram.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new guiOldProgram().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    // End of variables declaration//GEN-END:variables
}
